trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azure_subscription: luckyspnconnection
  tf_dir: '$(System.DefaultWorkingDirectory)'

stages:
- stage: Storage
  displayName: Storage
  jobs:
  - job: StorageJob
    displayName: Storage Job
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Run storage_account.sh
      inputs:
        azureSubscription: $(azure_subscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          chmod +x ./storage_account.sh
          ./storage_account.sh

- stage: Infra
  displayName: Infra Provisioning
  dependsOn: Storage
  jobs:
  - job: InfraJob
    displayName: Terraform Infra Job
    steps:
    - checkout: self

    - script: |
        set -e
        echo "Installing Terraform..."
        sudo apt-get update -y
        sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update -y
        sudo apt-get install terraform -y
        echo "Terraform installed at:"
        which terraform
        terraform -version
      displayName: Install Terraform CLI

    - task: AzureCLI@2
      displayName: Initializing Terraform
      inputs:
        azureSubscription: 'luckyspnconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(tf_dir)'
        inlineScript: 'terraform init'
    
    - task: AzureCLI@2
      displayName: Validating Terraform Files
      inputs:
        azureSubscription: 'luckyspnconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(tf_dir)'
        inlineScript: 'terraform validate'

    - task: AzureCLI@2
      displayName: Planning Resources
      inputs:
        azureSubscription: 'luckyspnconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(tf_dir)'
        inlineScript: 'terraform plan'
    
    - task: AzureCLI@2
      displayName: Apply Terraform
      inputs:
        azureSubscription: 'luckyspnconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'terraform apply --auto-approve'
        workingDirectory: '$(tf_dir)'
