trigger:
  - main

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'luckyconnect1234'
  webAppName: 'dotwebapp123456'

stages:
  # =========================
  # STAGE 1 – BUILD
  # =========================
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET SDK 8'
            inputs:
              packageType: 'sdk'
              version: '8.0.x'

          - script: dotnet restore eShopOnWeb.sln
            displayName: 'Restore'

          - script: dotnet build eShopOnWeb.sln --configuration $(buildConfiguration) --no-restore
            displayName: 'Build'

          - script: dotnet test eShopOnWeb.sln --configuration $(buildConfiguration) --no-build
            displayName: 'Run Tests'

          - script: |
              dotnet publish src/Web/Web.csproj ^
                --configuration $(buildConfiguration) ^
                --output $(Build.ArtifactStagingDirectory)/publish
            displayName: 'Publish'

          # Zip the publish output (best practice for AzureWebApp deployment)
          - task: ArchiveFiles@2
            displayName: 'Archive Published Output'
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop.zip'
              ArtifactName: 'drop'

  # =========================
  # STAGE 2 –   
  # =========================
  - stage: Deploy_Dev
    displayName: 'Deploy to Dev'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployDev
        displayName: 'Deploy Dev'
        environment: 'Dev'
        pool:
          vmImage: 'windows-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure Web App (Dev)'
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appName: '$(webAppName)'
                    package: '$(Pipeline.Workspace)/drop/drop.zip'

  # =========================
  # STAGE 3 – DEPLOY TO PROD
  # =========================
  - stage: Deploy_Prod
    displayName: 'Deploy to Prod'
    dependsOn: Deploy_Dev
    condition: succeeded()
    jobs:
      - deployment: DeployProd
        displayName: 'Deploy Prod'
        environment: 'Prod'
        pool:
          vmImage: 'windows-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure Web App (Prod)'
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appName: '$(webAppName)'
                    package: '$(Pipeline.Workspace)/drop/drop.zip'
