apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckywebapp
  labels:
    app: luckywebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luckywebapp
  template:
    metadata:
      labels:
        app: luckywebapp
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: luckywebapp
        image: luckyregistry.azurecr.io/luckypiece:latest
        ports:
        - containerPort: 80
